name: auto_release
on:
  push:
    branches:
      - main
jobs:
  releaser:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./Apps
          outPath: Apps.tar.gz
      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Create Release
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: '${{ steps.date.outputs.date }}'
          release-name: '${{ steps.date.outputs.date }}'
          asset-name: 'Apps.tar.gz'
          file: './Apps.tar.gz'
